'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CLub_Deportivo.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alevin_trucha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alevin-trucha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alevines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alevines", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alevines1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alevines1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alevines2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alevines2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alevines21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alevines21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bogas_saltando_en_el_medidor_de_aforos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bogas saltando en el medidor de aforos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 39626
        '''39549
        '''39549
        '''39210
        '''39639
        '''39549
        '''39698
        '''39761
        '''39780
        '''39670
        '''39880
        '''39880
        '''39719
        '''39213
        '''39849
        '''39806
        '''39728
        '''39170
        '''39680
        '''39683
        '''39419
        '''39292
        '''39584
        '''39849
        '''39813
        '''39232
        '''39798
        '''39649
        '''39880
        '''39193
        '''39791
        '''39840
        '''39718
        '''39197
        '''39794
        '''39788
        '''39727
        '''39571
        '''39592
        '''39849
        '''39212
        '''39220
        '''39430
        '''39478
        '''39419
        '''39627
        '''39553
        '''39450
        '''39593
        '''39232
        '''39777
        '''39582
        '''39626
        '''39197
        '''39586
        '''39593
        '''39212
        '''39584
        '''39195
        '''39813
        '''39419
        '''39360
        '''39213
        '''39577
        '''39232
        '''39806
        '''39813
        '''39610
        '''39806
        '''39813
        '''39572
        '''39360
        '''39108
        '''3 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property cantabria_cp() As String
            Get
                Return ResourceManager.GetString("cantabria_cp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ABADILLA, LA
        '''ABANILLAS
        '''ABAÑO
        '''ABIADA
        '''ABIONZO
        '''ACEBOSA, LA (ABANILLAS)
        '''ACEREDA
        '''ADAL
        '''ADINO
        '''AES
        '''AGUERA
        '''AGÜERA DE TRUCIOS
        '''AGÜERO
        '''AGUILERA, LA
        '''AHEDO (AMPUERO)
        '''AJA
        '''AJANEDO
        '''AJO
        '''ALCEDA
        '''ALDANO
        '''ALDEA DE EBRO
        '''ALDUESO
        '''ALIEZO
        '''ALISAS (AMPUERO)
        '''ALISAS (RAMALES)
        '''ALLEN DEL HOYO
        '''ALLENDELAGUA
        '''ALOÑOS
        '''ALTURA, LA
        '''ALVAREO, EL
        '''AMBROSERO
        '''AMPUERO
        '''ANAZ
        '''ANCILLO
        '''ANERO
        '''ANGOSTINA
        '''ANGUSTINA (RIOTUERTO)
        '''ANIEZO
        '''ANSAR, EL
        '''APARECIDA, LA
        '''ARADILLOS
        '''ARANTIONES
        '''ARCA
        '''ARCE
        '''ARCERA
        '''ARENAL DE PENAGOS, EL
        '''ARE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property cantabria_localidades() As String
            Get
                Return ResourceManager.GetString("cantabria_localidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CDB_PESCAREINOSA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CDB-PESCAREINOSA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property CDB_PESCAREINOSA_WEB() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CDB_PESCAREINOSA_WEB", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cola_rata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cola rata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Andalucia
        '''Aragon
        '''Principado de Asturias
        '''&quot;Islas Baleares
        '''(Illes Balears)&quot;
        '''&quot;Canarias
        '''(Islas)&quot;
        '''Cantabria
        '''Castilla y Leon
        '''Castilla La Mancha
        '''Cataluña
        '''Extremadura
        '''Galicia
        '''La Rioja
        '''Comunidad de Madrid
        '''Region de Murcia
        '''Comunidad Foral de Navarra
        '''Pais Vasco
        '''Comunidad Valenciana.
        '''</summary>
        Friend ReadOnly Property comunidades() As String
            Get
                Return ResourceManager.GetString("comunidades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ------ConfiguraciÃ³n - General------
        '''Temporada:
        '''2024
        '''Precio tarjeta  de Salmon(â‚¬):
        '''17
        '''Precio tarjeta  de Trucha(â‚¬):
        '''11
        '''------ConfiguraciÃ³n - Bases de datos------
        '''Tipo de base de datos:
        '''Excel_ODBC
        '''
        '''----Excel-ODBC----
        '''Archivo de base de datos:
        '''D:\Usuarios\roberto\OneDrive - Educantabria\Documentos\tarjetas_socio_2025.xls
        '''DSN:
        '''cdb-pesca-xlsx
        '''Tabla de socios:
        '''[socios_2024_25$]
        '''Tabla de base de datos de socios:
        '''[bdsocios$]
        '''
        '''----MySQL----
        '''Servidor:
        '''153.92.7.1
        '''Puerto:
        '''3306
        '''Base de da [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property configuracion() As String
            Get
                Return ResourceManager.GetString("configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Huevas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Huevas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Huevas_de_trucha_de_diferente_coloración_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Huevas de trucha de diferente coloración.", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A CORUÑA/LA CORUÑA 
        '''ALAVA/ARABA 
        '''ALBACETE 
        '''ALICANTE/ALACANT 
        '''ALMERIA 
        '''ASTURIAS 
        '''AVILA
        '''BADAJOZ
        '''BARCELONA
        '''BURGOS
        '''CACERES
        '''CADIZ
        '''CANTABRIA
        '''CASTELLON/CASTELLO
        '''CEUTA
        '''CIUDAD REAL
        '''CUENCA
        '''CORDOBA
        '''GIRONA/GERONA
        '''GRANADA
        '''GUADALAJARA
        '''GUIPUZKOA/GUIPUZCOA
        '''HUELVA
        '''HUESCA
        '''ILLES BALEARS/I. BALEARES
        '''JAEN
        '''LA RIOJA
        '''LAS PALMAS
        '''LEON
        '''LLEIDA/LERIDA
        '''LUGO
        '''MALAGA
        '''MADRID
        '''MELILLA
        '''MURCIA
        '''NAVARRA
        '''OURENSE/ORENSE
        '''PALENCIA
        '''PONTEVEDRA
        '''SALAMANCA
        '''SEGOVIA
        '''SEVILLA
        '''SORIA
        '''STA CRUZ DE TENERIFE
        '''TARRAGONA
        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property provincias() As String
            Get
                Return ResourceManager.GetString("provincias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarjeta_socio_anverso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarjeta_socio_anverso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tarjeta_socio_reverso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tarjeta_socio_reverso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
